-file("/Users/barbarachassoul/.asdf/installs/erlang/26.2.5.4/lib/parsetools-2.5/include/leexinc.hrl", 0).
%% The source of this file is part of leex distribution, as such it
%% has the same Copyright as the other files in the leex
%% distribution. The Copyright is defined in the accompanying file
%% COPYRIGHT. However, the resultant scanner generated by leex is the
%% property of the creator of the scanner and is not covered by that
%% Copyright.

-module(physerl_lexer).

-export([string/1,string/2,token/2,token/3,tokens/2,tokens/3]).
-export([format_error/1]).

%% User code. This is placed here to allow extra attributes.
-file("/Users/barbarachassoul/Library/Mobile Documents/com~apple~CloudDocs/physerl/src/physerl_lexer.xrl", 80).

-file("/Users/barbarachassoul/.asdf/installs/erlang/26.2.5.4/lib/parsetools-2.5/include/leexinc.hrl", 14).

format_error({illegal,S}) -> ["illegal characters ",io_lib:write_string(S)];
format_error({user,S}) -> S.

%% string(InChars) ->
%% string(InChars, Loc) ->
%% {ok,Tokens,EndLoc} | {error,ErrorInfo,EndLoc}.
%% Loc is the starting location of the token, while EndLoc is the first not scanned
%% location. Location is either Line or {Line,Column}, depending on the "error_location" option.

string(Ics) -> 
    string(Ics,1).
string(Ics,L0) -> 
    string(Ics, L0, 1, Ics, []).
string(Ics, L0, C0, Tcs, Ts) -> 
    case do_string(Ics, L0, C0, Tcs, Ts) of
        {ok, T, {L,_}} -> {ok, T, L};
        {error, {{EL,_},M,D}, {L,_}} ->
            EI = {EL,M,D},
            {error, EI, L}
    end.

do_string([], L, C, [], Ts) ->                     % No partial tokens!
    {ok,yyrev(Ts),{L,C}};
do_string(Ics0, L0, C0, Tcs, Ts) ->
    case yystate(yystate(), Ics0, L0, C0, 0, reject, 0) of
        {A,Alen,Ics1,L1,_C1} ->                  % Accepting end state
            C2 = adjust_col(Tcs, Alen, C0),
            string_cont(Ics1, L1, C2, yyaction(A, Alen, Tcs, L0, C0), Ts);
        {A,Alen,Ics1,L1,_C1,_S1} ->              % Accepting transition state
            C2 = adjust_col(Tcs, Alen, C0),
            string_cont(Ics1, L1, C2, yyaction(A, Alen, Tcs, L0, C0), Ts);
        {reject,_Alen,Tlen,_Ics1,_L1,_C1,_S1} ->  % After a non-accepting state
            {error,{{L0, C0} ,?MODULE,{illegal,yypre(Tcs, Tlen+1)}},{L0, C0}};
        {A,Alen,Tlen,_Ics1,L1, C1,_S1}->
            Tcs1 = yysuf(Tcs, Alen),
            L2 = adjust_line(Tlen, Alen, Tcs1, L1),
            C2 = adjust_col(Tcs, Alen, C1),
            string_cont(Tcs1, L2, C2, yyaction(A, Alen, Tcs, L0,C0), Ts)
    end.

%% string_cont(RestChars, Line, Col, Token, Tokens)
%% Test for and remove the end token wrapper. Push back characters
%% are prepended to RestChars.

-dialyzer({nowarn_function, string_cont/5}).

string_cont(Rest, Line, Col, {token,T}, Ts) ->
    do_string(Rest, Line, Col, Rest, [T|Ts]);
string_cont(Rest, Line, Col, {token,T,Push}, Ts) ->
    NewRest = Push ++ Rest,
    do_string(NewRest, Line, Col, NewRest, [T|Ts]);
string_cont(Rest, Line, Col, {end_token,T}, Ts) ->
    do_string(Rest, Line, Col, Rest, [T|Ts]);
string_cont(Rest, Line, Col, {end_token,T,Push}, Ts) ->
    NewRest = Push ++ Rest,
    do_string(NewRest, Line, Col, NewRest, [T|Ts]);
string_cont(Rest, Line, Col, skip_token, Ts) ->
    do_string(Rest, Line, Col, Rest, Ts);
string_cont(Rest, Line, Col, {skip_token,Push}, Ts) ->
    NewRest = Push ++ Rest,
    do_string(NewRest, Line, Col, NewRest, Ts);
string_cont(_Rest, Line, Col, {error,S}, _Ts) ->
    {error,{{Line, Col},?MODULE,{user,S}},{Line,Col}}.

%% token(Continuation, Chars) ->
%% token(Continuation, Chars, Loc) ->
%% {more,Continuation} | {done,ReturnVal,RestChars}.
%% Must be careful when re-entering to append the latest characters to the
%% after characters in an accept. The continuation is:
%% {token,State,CurrLine,CurrCol,TokenChars,TokenLen,TokenLine,TokenCol,AccAction,AccLen}

token(Cont,Chars) -> 
    token(Cont,Chars,1).
token(Cont, Chars, Line) -> 
    case do_token(Cont,Chars,Line,1) of
        {more, _} = C -> C;
        {done, Ret0, R} ->
            Ret1 = case Ret0 of
                {ok, T, {L,_}} -> {ok, T, L};
                {eof, {L,_}} -> {eof, L};
                {error, {{EL,_},M,D},{L,_}} -> {error, {EL,M,D},L}
            end,
            {done, Ret1, R}
    end.

do_token([], Chars, Line, Col) ->
    token(yystate(), Chars, Line, Col, Chars, 0, Line, Col, reject, 0);
do_token({token,State,Line,Col,Tcs,Tlen,Tline,Tcol,Action,Alen}, Chars, _, _) ->
    token(State, Chars, Line, Col, Tcs ++ Chars, Tlen, Tline, Tcol, Action, Alen).

%% token(State, InChars, Line, Col, TokenChars, TokenLen, TokenLine, TokenCol
%% AcceptAction, AcceptLen) ->
%% {more,Continuation} | {done,ReturnVal,RestChars}.
%% The argument order is chosen to be more efficient.

token(S0, Ics0, L0, C0, Tcs, Tlen0, Tline, Tcol, A0, Alen0) ->
    case yystate(S0, Ics0, L0, C0, Tlen0, A0, Alen0) of
        %% Accepting end state, we have a token.
        {A1,Alen1,Ics1,L1,C1} ->
            C2 = adjust_col(Tcs, Alen1, C1),
            token_cont(Ics1, L1, C2, yyaction(A1, Alen1, Tcs, Tline,Tcol));
        %% Accepting transition state, can take more chars.
        {A1,Alen1,[],L1,C1,S1} ->                  % Need more chars to check
            {more,{token,S1,L1,C1,Tcs,Alen1,Tline,Tcol,A1,Alen1}};
        {A1,Alen1,Ics1,L1,C1,_S1} ->               % Take what we got
            C2 = adjust_col(Tcs, Alen1, C1),
            token_cont(Ics1, L1, C2, yyaction(A1, Alen1, Tcs, Tline,Tcol));
        %% After a non-accepting state, maybe reach accept state later.
        {A1,Alen1,Tlen1,[],L1,C1,S1} ->            % Need more chars to check
            {more,{token,S1,L1,C1,Tcs,Tlen1,Tline,Tcol,A1,Alen1}};
        {reject,_Alen1,Tlen1,eof,L1,C1,_S1} ->     % No token match
            %% Check for partial token which is error.
            Ret = if Tlen1 > 0 -> {error,{{Tline,Tcol},?MODULE,
                                          %% Skip eof tail in Tcs.
                                          {illegal,yypre(Tcs, Tlen1)}},{L1,C1}};
                     true -> {eof,{L1,C1}}
                  end,
            {done,Ret,eof};
        {reject,_Alen1,Tlen1,Ics1,_L1,_C1,_S1} ->    % No token match
            Error = {{Tline,Tcol},?MODULE,{illegal,yypre(Tcs, Tlen1+1)}},
            {done,{error,Error,{Tline,Tcol}},Ics1};
        {A1,Alen1,Tlen1,_Ics1,L1,_C1,_S1} ->       % Use last accept match
            Tcs1 = yysuf(Tcs, Alen1),
            L2 = adjust_line(Tlen1, Alen1, Tcs1, L1),
            C2 = C0 + Alen1,
            token_cont(Tcs1, L2, C2, yyaction(A1, Alen1, Tcs, Tline, Tcol))
    end.

%% token_cont(RestChars, Line, Col, Token)
%% If we have a token or error then return done, else if we have a
%% skip_token then continue.

-dialyzer({nowarn_function, token_cont/4}).

token_cont(Rest, Line, Col, {token,T}) ->
    {done,{ok,T,{Line,Col}},Rest};
token_cont(Rest, Line, Col, {token,T,Push}) ->
    NewRest = Push ++ Rest,
    {done,{ok,T,{Line,Col}},NewRest};
token_cont(Rest, Line, Col, {end_token,T}) ->
    {done,{ok,T,{Line,Col}},Rest};
token_cont(Rest, Line, Col, {end_token,T,Push}) ->
    NewRest = Push ++ Rest,
    {done,{ok,T,{Line,Col}},NewRest};
token_cont(Rest, Line, Col, skip_token) ->
    token(yystate(), Rest, Line, Col, Rest, 0, Line, Col, reject, 0);
token_cont(Rest, Line, Col, {skip_token,Push}) ->
    NewRest = Push ++ Rest,
    token(yystate(), NewRest, Line, Col, NewRest, 0, Line, Col, reject, 0);
token_cont(Rest, Line, Col, {error,S}) ->
    {done,{error,{{Line, Col},?MODULE,{user,S}},{Line, Col}},Rest}.

%% tokens(Continuation, Chars) ->
%% tokens(Continuation, Chars, Loc) ->
%% {more,Continuation} | {done,ReturnVal,RestChars}.
%% Must be careful when re-entering to append the latest characters to the
%% after characters in an accept. The continuation is:
%% {tokens,State,CurrLine,CurrCol,TokenChars,TokenLen,TokenLine,TokenCur,Tokens,AccAction,AccLen}
%% {skip_tokens,State,CurrLine,CurrCol,TokenChars,TokenLen,TokenLine,TokenCur,Error,AccAction,AccLen}

tokens(Cont,Chars) -> 
    tokens(Cont,Chars,1).
tokens(Cont, Chars, Line) -> 
    case do_tokens(Cont,Chars,Line,1) of
        {more, _} = C -> C;
        {done, Ret0, R} ->
            Ret1 = case Ret0 of
                {ok, T, {L,_}} -> {ok, T, L};
                {eof, {L,_}} -> {eof, L};
                {error, {{EL,_},M,D},{L,_}} -> {error, {EL,M,D},L}
            end,
            {done, Ret1, R}
    end.

do_tokens([], Chars, Line, Col) ->
    tokens(yystate(), Chars, Line, Col, Chars, 0, Line, Col, [], reject, 0);
do_tokens({tokens,State,Line,Col,Tcs,Tlen,Tline,Tcol,Ts,Action,Alen}, Chars, _,_) ->
    tokens(State, Chars, Line, Col, Tcs ++ Chars, Tlen, Tline, Tcol, Ts, Action, Alen);
do_tokens({skip_tokens,State,Line, Col, Tcs,Tlen,Tline,Tcol,Error,Action,Alen}, Chars, _,_) ->
    skip_tokens(State, Chars, Line, Col, Tcs ++ Chars, Tlen, Tline, Tcol, Error, Action, Alen).

%% tokens(State, InChars, Line, Col, TokenChars, TokenLen, TokenLine, TokenCol,Tokens,
%% AcceptAction, AcceptLen) ->
%% {more,Continuation} | {done,ReturnVal,RestChars}.

tokens(S0, Ics0, L0, C0, Tcs, Tlen0, Tline, Tcol, Ts, A0, Alen0) ->
    case yystate(S0, Ics0, L0, C0, Tlen0, A0, Alen0) of
        %% Accepting end state, we have a token.
        {A1,Alen1,Ics1,L1,C1} ->
            C2 = adjust_col(Tcs, Alen1, C1),
            tokens_cont(Ics1, L1, C2, yyaction(A1, Alen1, Tcs, Tline, Tcol), Ts);
        %% Accepting transition state, can take more chars.
        {A1,Alen1,[],L1,C1,S1} ->                  % Need more chars to check
            {more,{tokens,S1,L1,C1,Tcs,Alen1,Tline,Tcol,Ts,A1,Alen1}};
        {A1,Alen1,Ics1,L1,C1,_S1} ->               % Take what we got
            C2 = adjust_col(Tcs, Alen1, C1),
            tokens_cont(Ics1, L1, C2, yyaction(A1, Alen1, Tcs, Tline,Tcol), Ts);
        %% After a non-accepting state, maybe reach accept state later.
        {A1,Alen1,Tlen1,[],L1,C1,S1} ->            % Need more chars to check
            {more,{tokens,S1,L1,C1,Tcs,Tlen1,Tline,Tcol,Ts,A1,Alen1}};
        {reject,_Alen1,Tlen1,eof,L1,C1,_S1} ->     % No token match
            %% Check for partial token which is error, no need to skip here.
            Ret = if Tlen1 > 0 -> {error,{{Tline,Tcol},?MODULE,
                                          %% Skip eof tail in Tcs.
                                          {illegal,yypre(Tcs, Tlen1)}},{L1,C1}};
                     Ts == [] -> {eof,{L1,C1}};
                     true -> {ok,yyrev(Ts),{L1,C1}}
                  end,
            {done,Ret,eof};
        {reject,_Alen1,Tlen1,_Ics1,L1,C1,_S1} ->
            %% Skip rest of tokens.
            Error = {{L1,C1},?MODULE,{illegal,yypre(Tcs, Tlen1+1)}},
            skip_tokens(yysuf(Tcs, Tlen1+1), L1, C1, Error);
        {A1,Alen1,Tlen1,_Ics1,L1,_C1,_S1} ->
            Token = yyaction(A1, Alen1, Tcs, Tline,Tcol),
            Tcs1 = yysuf(Tcs, Alen1),
            L2 = adjust_line(Tlen1, Alen1, Tcs1, L1),
            C2 = C0 + Alen1,
            tokens_cont(Tcs1, L2, C2, Token, Ts)
    end.

%% tokens_cont(RestChars, Line, Column, Token, Tokens)
%% If we have an end_token or error then return done, else if we have
%% a token then save it and continue, else if we have a skip_token
%% just continue.

-dialyzer({nowarn_function, tokens_cont/5}).

tokens_cont(Rest, Line, Col, {token,T}, Ts) ->
    tokens(yystate(), Rest, Line, Col, Rest, 0, Line, Col, [T|Ts], reject, 0);
tokens_cont(Rest, Line, Col, {token,T,Push}, Ts) ->
    NewRest = Push ++ Rest,
    tokens(yystate(), NewRest, Line, Col, NewRest, 0, Line, Col, [T|Ts], reject, 0);
tokens_cont(Rest, Line, Col, {end_token,T}, Ts) ->
    {done,{ok,yyrev(Ts, [T]),{Line,Col}},Rest};
tokens_cont(Rest, Line, Col, {end_token,T,Push}, Ts) ->
    NewRest = Push ++ Rest,
    {done,{ok,yyrev(Ts, [T]),{Line, Col}},NewRest};
tokens_cont(Rest, Line, Col, skip_token, Ts) ->
    tokens(yystate(), Rest, Line, Col, Rest, 0, Line, Col, Ts, reject, 0);
tokens_cont(Rest, Line, Col, {skip_token,Push}, Ts) ->
    NewRest = Push ++ Rest,
    tokens(yystate(), NewRest, Line, Col, NewRest, 0, Line, Col, Ts, reject, 0);
tokens_cont(Rest, Line, Col, {error,S}, _Ts) ->
    skip_tokens(Rest, Line, Col, {{Line,Col},?MODULE,{user,S}}).

%% skip_tokens(InChars, Line, Col, Error) -> {done,{error,Error,{Line,Col}},Ics}.
%% Skip tokens until an end token, junk everything and return the error.

skip_tokens(Ics, Line, Col, Error) ->
    skip_tokens(yystate(), Ics, Line, Col, Ics, 0, Line, Col, Error, reject, 0).

%% skip_tokens(State, InChars, Line, Col, TokenChars, TokenLen, TokenLine, TokenCol, Tokens,
%% AcceptAction, AcceptLen) ->
%% {more,Continuation} | {done,ReturnVal,RestChars}.

skip_tokens(S0, Ics0, L0, C0, Tcs, Tlen0, Tline, Tcol, Error, A0, Alen0) ->
    case yystate(S0, Ics0, L0, C0, Tlen0, A0, Alen0) of
        {A1,Alen1,Ics1,L1, C1} ->                  % Accepting end state
            skip_cont(Ics1, L1, C1, yyaction(A1, Alen1, Tcs, Tline, Tcol), Error);
        {A1,Alen1,[],L1,C1, S1} ->                 % After an accepting state
            {more,{skip_tokens,S1,L1,C1,Tcs,Alen1,Tline,Tcol,Error,A1,Alen1}};
        {A1,Alen1,Ics1,L1,C1,_S1} ->
            skip_cont(Ics1, L1, C1, yyaction(A1, Alen1, Tcs, Tline, Tcol), Error);
        {A1,Alen1,Tlen1,[],L1,C1,S1} ->           % After a non-accepting state
            {more,{skip_tokens,S1,L1,C1,Tcs,Tlen1,Tline,Tcol,Error,A1,Alen1}};
        {reject,_Alen1,_Tlen1,eof,L1,C1,_S1} ->
            {done,{error,Error,{L1,C1}},eof};
        {reject,_Alen1,Tlen1,_Ics1,L1,C1,_S1} ->
            skip_tokens(yysuf(Tcs, Tlen1+1), L1, C1,Error);
        {A1,Alen1,Tlen1,_Ics1,L1,C1,_S1} ->
            Token = yyaction(A1, Alen1, Tcs, Tline, Tcol),
            Tcs1 = yysuf(Tcs, Alen1),
            L2 = adjust_line(Tlen1, Alen1, Tcs1, L1),
            skip_cont(Tcs1, L2, C1, Token, Error)
    end.

%% skip_cont(RestChars, Line, Col, Token, Error)
%% Skip tokens until we have an end_token or error then return done
%% with the original rror.

-dialyzer({nowarn_function, skip_cont/5}).

skip_cont(Rest, Line, Col, {token,_T}, Error) ->
    skip_tokens(yystate(), Rest, Line, Col, Rest, 0, Line, Col, Error, reject, 0);
skip_cont(Rest, Line, Col, {token,_T,Push}, Error) ->
    NewRest = Push ++ Rest,
    skip_tokens(yystate(), NewRest, Line, Col, NewRest, 0, Line, Col, Error, reject, 0);
skip_cont(Rest, Line, Col, {end_token,_T}, Error) ->
    {done,{error,Error,{Line,Col}},Rest};
skip_cont(Rest, Line, Col, {end_token,_T,Push}, Error) ->
    NewRest = Push ++ Rest,
    {done,{error,Error,{Line,Col}},NewRest};
skip_cont(Rest, Line, Col, skip_token, Error) ->
    skip_tokens(yystate(), Rest, Line, Col, Rest, 0, Line, Col, Error, reject, 0);
skip_cont(Rest, Line, Col, {skip_token,Push}, Error) ->
    NewRest = Push ++ Rest,
    skip_tokens(yystate(), NewRest, Line, Col, NewRest, 0, Line, Col, Error, reject, 0);
skip_cont(Rest, Line, Col, {error,_S}, Error) ->
    skip_tokens(yystate(), Rest, Line, Col, Rest, 0, Line, Col, Error, reject, 0).

-compile({nowarn_unused_function, [yyrev/1, yyrev/2, yypre/2, yysuf/2]}).

yyrev(List) -> lists:reverse(List).
yyrev(List, Tail) -> lists:reverse(List, Tail).
yypre(List, N) -> lists:sublist(List, N).
yysuf(List, N) -> lists:nthtail(N, List).

%% adjust_line(TokenLength, AcceptLength, Chars, Line) -> NewLine
%% Make sure that newlines in Chars are not counted twice.
%% Line has been updated with respect to newlines in the prefix of
%% Chars consisting of (TokenLength - AcceptLength) characters.

-compile({nowarn_unused_function, adjust_line/4}).

adjust_line(N, N, _Cs, L) -> L;
adjust_line(T, A, [$\n|Cs], L) ->
    adjust_line(T-1, A, Cs, L-1);
adjust_line(T, A, [_|Cs], L) ->
    adjust_line(T-1, A, Cs, L).

%% adjust_col(Chars, AcceptLength, Col) -> NewCol
%% Handle newlines, tabs and unicode chars.
adjust_col(_, 0, Col) ->
    Col;
adjust_col([$\n | R], L, _) ->
    adjust_col(R, L-1, 1);
adjust_col([$\t | R], L, Col) ->
    adjust_col(R, L-1, tab_forward(Col)+1);
adjust_col([C | R], L, Col) when C>=0 andalso C=< 16#7F ->
    adjust_col(R, L-1, Col+1);
adjust_col([C | R], L, Col) when C>= 16#80 andalso C=< 16#7FF ->
    adjust_col(R, L-1, Col+2);
adjust_col([C | R], L, Col) when C>= 16#800 andalso C=< 16#FFFF ->
    adjust_col(R, L-1, Col+3);
adjust_col([C | R], L, Col) when C>= 16#10000 andalso C=< 16#10FFFF ->
    adjust_col(R, L-1, Col+4).

tab_forward(C) ->
    D = C rem tab_size(),
    A = tab_size()-D,
    C+A.

tab_size() -> 8.

%% yystate() -> InitialState.
%% yystate(State, InChars, Line, Col, CurrTokLen, AcceptAction, AcceptLen) ->
%% {Action, AcceptLen, RestChars, Line, Col} |
%% {Action, AcceptLen, RestChars, Line, Col, State} |
%% {reject, AcceptLen, CurrTokLen, RestChars, Line, Col, State} |
%% {Action, AcceptLen, CurrTokLen, RestChars, Line, Col, State}.
%% Generated state transition functions. The non-accepting end state
%% return signal either an unrecognised character or end of current
%% input.

-file("/Users/barbarachassoul/Library/Mobile Documents/com~apple~CloudDocs/physerl/src/physerl_lexer.erl", 339).
yystate() -> 65.

yystate(68, [118|Ics], Line, Col, Tlen, _, _) ->
    yystate(64, Ics, Line, Col, Tlen+1, 48, Tlen);
yystate(68, Ics, Line, Col, Tlen, _, _) ->
    {48,Tlen,Ics,Line,Col,68};
yystate(67, Ics, Line, Col, Tlen, _, _) ->
    {58,Tlen,Ics,Line,Col};
yystate(66, Ics, Line, Col, Tlen, _, _) ->
    {18,Tlen,Ics,Line,Col};
yystate(65, [956|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(61, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(65, [122|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(57, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(65, [121|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(53, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(65, [115|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(49, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(65, [114|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(45, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(65, [113|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(41, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(65, [112|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(37, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(65, [111|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(67, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(65, [110|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(33, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(65, [109|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(29, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(65, [108|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(17, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(65, [107|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(5, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(65, [105|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(67, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(65, [106|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(67, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(65, [104|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(10, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(65, [103|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(14, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(65, [102|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(18, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(65, [101|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(67, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(65, [100|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(22, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(65, [99|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(30, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(65, [98|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(67, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(65, [97|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(38, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(65, [95|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(67, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(65, [96|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(67, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(65, [94|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(42, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(65, [90|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(46, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(65, [89|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(50, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(65, [88|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(67, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(65, [87|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(54, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(65, [86|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(62, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(65, [85|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(67, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(65, [84|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(66, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(65, [83|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(68, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(65, [82|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(60, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(65, [81|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(56, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(65, [80|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(52, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(65, [79|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(44, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(65, [78|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(32, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(65, [77|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(28, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(65, [76|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(67, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(65, [75|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(24, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(65, [74|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(20, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(65, [73|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(67, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(65, [72|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(16, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(65, [71|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(8, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(65, [70|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(0, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(65, [69|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(3, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(65, [68|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(67, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(65, [67|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(7, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(65, [66|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(11, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(65, [65|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(19, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(65, [47|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(47, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(65, [46|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(67, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(65, [45|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(51, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(65, [44|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(67, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(65, [43|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(55, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(65, [42|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(59, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(65, [32|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(63, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(65, [9|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(63, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(65, [C|Ics], Line, Col, Tlen, Action, Alen) when C >= 0, C =< 8 ->
    yystate(67, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(65, [C|Ics], Line, Col, Tlen, Action, Alen) when C >= 11, C =< 31 ->
    yystate(67, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(65, [C|Ics], Line, Col, Tlen, Action, Alen) when C >= 33, C =< 41 ->
    yystate(67, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(65, [C|Ics], Line, Col, Tlen, Action, Alen) when C >= 48, C =< 57 ->
    yystate(35, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(65, [C|Ics], Line, Col, Tlen, Action, Alen) when C >= 58, C =< 64 ->
    yystate(67, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(65, [C|Ics], Line, Col, Tlen, Action, Alen) when C >= 91, C =< 93 ->
    yystate(67, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(65, [C|Ics], Line, Col, Tlen, Action, Alen) when C >= 116, C =< 120 ->
    yystate(67, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(65, [C|Ics], Line, Col, Tlen, Action, Alen) when C >= 123, C =< 955 ->
    yystate(67, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(65, [C|Ics], Line, Col, Tlen, Action, Alen) when C >= 957 ->
    yystate(67, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(65, Ics, Line, Col, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,Col,65};
yystate(64, Ics, Line, Col, Tlen, _, _) ->
    {56,Tlen,Ics,Line,Col};
yystate(63, Ics, Line, Col, Tlen, _, _) ->
    {7,Tlen,Ics,Line,Col};
yystate(62, Ics, Line, Col, Tlen, _, _) ->
    {45,Tlen,Ics,Line,Col};
yystate(61, Ics, Line, Col, Tlen, _, _) ->
    {25,Tlen,Ics,Line,Col};
yystate(60, Ics, Line, Col, Tlen, _, _) ->
    {13,Tlen,Ics,Line,Col};
yystate(59, Ics, Line, Col, Tlen, _, _) ->
    {5,Tlen,Ics,Line,Col};
yystate(58, Ics, Line, Col, Tlen, _, _) ->
    {49,Tlen,Ics,Line,Col};
yystate(57, Ics, Line, Col, Tlen, _, _) ->
    {30,Tlen,Ics,Line,Col};
yystate(56, Ics, Line, Col, Tlen, _, _) ->
    {12,Tlen,Ics,Line,Col};
yystate(55, Ics, Line, Col, Tlen, _, _) ->
    {3,Tlen,Ics,Line,Col};
yystate(54, [98|Ics], Line, Col, Tlen, _, _) ->
    yystate(58, Ics, Line, Col, Tlen+1, 43, Tlen);
yystate(54, Ics, Line, Col, Tlen, _, _) ->
    {43,Tlen,Ics,Line,Col,54};
yystate(53, Ics, Line, Col, Tlen, _, _) ->
    {31,Tlen,Ics,Line,Col};
yystate(52, [97|Ics], Line, Col, Tlen, _, _) ->
    yystate(48, Ics, Line, Col, Tlen+1, 17, Tlen);
yystate(52, Ics, Line, Col, Tlen, _, _) ->
    {17,Tlen,Ics,Line,Col,52};
yystate(51, Ics, Line, Col, Tlen, _, _) ->
    {4,Tlen,Ics,Line,Col};
yystate(50, Ics, Line, Col, Tlen, _, _) ->
    {14,Tlen,Ics,Line,Col};
yystate(49, Ics, Line, Col, Tlen, _, _) ->
    {34,Tlen,Ics,Line,Col};
yystate(48, Ics, Line, Col, Tlen, _, _) ->
    {41,Tlen,Ics,Line,Col};
yystate(47, Ics, Line, Col, Tlen, _, _) ->
    {6,Tlen,Ics,Line,Col};
yystate(46, Ics, Line, Col, Tlen, _, _) ->
    {15,Tlen,Ics,Line,Col};
yystate(45, Ics, Line, Col, Tlen, _, _) ->
    {32,Tlen,Ics,Line,Col};
yystate(44, [104|Ics], Line, Col, Tlen, _, _) ->
    yystate(40, Ics, Line, Col, Tlen+1, 58, Tlen);
yystate(44, Ics, Line, Col, Tlen, _, _) ->
    {58,Tlen,Ics,Line,Col,44};
yystate(43, [101|Ics], Line, Col, Tlen, _, _) ->
    yystate(23, Ics, Line, Col, Tlen+1, 1, Tlen);
yystate(43, [69|Ics], Line, Col, Tlen, _, _) ->
    yystate(23, Ics, Line, Col, Tlen+1, 1, Tlen);
yystate(43, [C|Ics], Line, Col, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(43, Ics, Line, Col, Tlen+1, 1, Tlen);
yystate(43, Ics, Line, Col, Tlen, _, _) ->
    {1,Tlen,Ics,Line,Col,43};
yystate(42, Ics, Line, Col, Tlen, _, _) ->
    {2,Tlen,Ics,Line,Col};
yystate(41, Ics, Line, Col, Tlen, _, _) ->
    {33,Tlen,Ics,Line,Col};
yystate(40, [109|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(36, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(40, Ics, Line, Col, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,Col,40};
yystate(39, [C|Ics], Line, Col, Tlen, Action, Alen) when C >= 48, C =< 57 ->
    yystate(43, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(39, Ics, Line, Col, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,Col,39};
yystate(38, Ics, Line, Col, Tlen, _, _) ->
    {29,Tlen,Ics,Line,Col};
yystate(37, Ics, Line, Col, Tlen, _, _) ->
    {27,Tlen,Ics,Line,Col};
yystate(36, Ics, Line, Col, Tlen, _, _) ->
    {47,Tlen,Ics,Line,Col};
yystate(35, [101|Ics], Line, Col, Tlen, _, _) ->
    yystate(23, Ics, Line, Col, Tlen+1, 0, Tlen);
yystate(35, [69|Ics], Line, Col, Tlen, _, _) ->
    yystate(23, Ics, Line, Col, Tlen+1, 0, Tlen);
yystate(35, [46|Ics], Line, Col, Tlen, _, _) ->
    yystate(39, Ics, Line, Col, Tlen+1, 0, Tlen);
yystate(35, [C|Ics], Line, Col, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(35, Ics, Line, Col, Tlen+1, 0, Tlen);
yystate(35, Ics, Line, Col, Tlen, _, _) ->
    {0,Tlen,Ics,Line,Col,35};
yystate(34, Ics, Line, Col, Tlen, _, _) ->
    {38,Tlen,Ics,Line,Col};
yystate(33, Ics, Line, Col, Tlen, _, _) ->
    {26,Tlen,Ics,Line,Col};
yystate(32, Ics, Line, Col, Tlen, _, _) ->
    {40,Tlen,Ics,Line,Col};
yystate(31, [C|Ics], Line, Col, Tlen, Action, Alen) when C >= 48, C =< 57 ->
    yystate(27, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(31, Ics, Line, Col, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,Col,31};
yystate(30, [100|Ics], Line, Col, Tlen, _, _) ->
    yystate(34, Ics, Line, Col, Tlen+1, 24, Tlen);
yystate(30, Ics, Line, Col, Tlen, _, _) ->
    {24,Tlen,Ics,Line,Col,30};
yystate(29, [111|Ics], Line, Col, Tlen, _, _) ->
    yystate(25, Ics, Line, Col, Tlen+1, 11, Tlen);
yystate(29, Ics, Line, Col, Tlen, _, _) ->
    {11,Tlen,Ics,Line,Col,29};
yystate(28, Ics, Line, Col, Tlen, _, _) ->
    {20,Tlen,Ics,Line,Col};
yystate(27, [C|Ics], Line, Col, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(27, Ics, Line, Col, Tlen+1, 1, Tlen);
yystate(27, Ics, Line, Col, Tlen, _, _) ->
    {1,Tlen,Ics,Line,Col,27};
yystate(26, Ics, Line, Col, Tlen, _, _) ->
    {22,Tlen,Ics,Line,Col};
yystate(25, [108|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(21, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(25, Ics, Line, Col, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,Col,25};
yystate(24, Ics, Line, Col, Tlen, _, _) ->
    {36,Tlen,Ics,Line,Col};
yystate(23, [45|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(31, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(23, [43|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(31, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(23, [C|Ics], Line, Col, Tlen, Action, Alen) when C >= 48, C =< 57 ->
    yystate(27, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(23, Ics, Line, Col, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,Col,23};
yystate(22, [97|Ics], Line, Col, Tlen, _, _) ->
    yystate(26, Ics, Line, Col, Tlen+1, 23, Tlen);
yystate(22, Ics, Line, Col, Tlen, _, _) ->
    {23,Tlen,Ics,Line,Col,22};
yystate(21, Ics, Line, Col, Tlen, _, _) ->
    {37,Tlen,Ics,Line,Col};
yystate(20, Ics, Line, Col, Tlen, _, _) ->
    {42,Tlen,Ics,Line,Col};
yystate(19, Ics, Line, Col, Tlen, _, _) ->
    {35,Tlen,Ics,Line,Col};
yystate(18, Ics, Line, Col, Tlen, _, _) ->
    {28,Tlen,Ics,Line,Col};
yystate(17, [120|Ics], Line, Col, Tlen, _, _) ->
    yystate(13, Ics, Line, Col, Tlen+1, 58, Tlen);
yystate(17, [109|Ics], Line, Col, Tlen, _, _) ->
    yystate(9, Ics, Line, Col, Tlen+1, 58, Tlen);
yystate(17, Ics, Line, Col, Tlen, _, _) ->
    {58,Tlen,Ics,Line,Col,17};
yystate(16, [122|Ics], Line, Col, Tlen, _, _) ->
    yystate(12, Ics, Line, Col, Tlen+1, 51, Tlen);
yystate(16, Ics, Line, Col, Tlen, _, _) ->
    {51,Tlen,Ics,Line,Col,16};
yystate(15, Ics, Line, Col, Tlen, _, _) ->
    {54,Tlen,Ics,Line,Col};
yystate(14, Ics, Line, Col, Tlen, _, _) ->
    {10,Tlen,Ics,Line,Col};
yystate(13, Ics, Line, Col, Tlen, _, _) ->
    {53,Tlen,Ics,Line,Col};
yystate(12, Ics, Line, Col, Tlen, _, _) ->
    {39,Tlen,Ics,Line,Col};
yystate(11, [113|Ics], Line, Col, Tlen, _, _) ->
    yystate(15, Ics, Line, Col, Tlen+1, 58, Tlen);
yystate(11, Ics, Line, Col, Tlen, _, _) ->
    {58,Tlen,Ics,Line,Col,11};
yystate(10, Ics, Line, Col, Tlen, _, _) ->
    {21,Tlen,Ics,Line,Col};
yystate(9, Ics, Line, Col, Tlen, _, _) ->
    {52,Tlen,Ics,Line,Col};
yystate(8, [121|Ics], Line, Col, Tlen, _, _) ->
    yystate(4, Ics, Line, Col, Tlen+1, 19, Tlen);
yystate(8, Ics, Line, Col, Tlen, _, _) ->
    {19,Tlen,Ics,Line,Col,8};
yystate(7, Ics, Line, Col, Tlen, _, _) ->
    {44,Tlen,Ics,Line,Col};
yystate(6, Ics, Line, Col, Tlen, _, _) ->
    {57,Tlen,Ics,Line,Col};
yystate(5, [103|Ics], Line, Col, Tlen, _, _) ->
    yystate(1, Ics, Line, Col, Tlen+1, 9, Tlen);
yystate(5, [97|Ics], Line, Col, Tlen, _, _) ->
    yystate(2, Ics, Line, Col, Tlen+1, 9, Tlen);
yystate(5, Ics, Line, Col, Tlen, _, _) ->
    {9,Tlen,Ics,Line,Col,5};
yystate(4, Ics, Line, Col, Tlen, _, _) ->
    {55,Tlen,Ics,Line,Col};
yystate(3, Ics, Line, Col, Tlen, _, _) ->
    {16,Tlen,Ics,Line,Col};
yystate(2, [116|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(6, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(2, Ics, Line, Col, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,Col,2};
yystate(1, Ics, Line, Col, Tlen, _, _) ->
    {8,Tlen,Ics,Line,Col};
yystate(0, Ics, Line, Col, Tlen, _, _) ->
    {46,Tlen,Ics,Line,Col};
yystate(S, Ics, Line, Col, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,Col,S}.

%% yyaction(Action, TokenLength, TokenChars, TokenLine, TokenCol) ->
%% {token,Token} | {end_token, Token} | skip_token | {error,String}.
%% Generated action function.

yyaction(0, TokenLen, YYtcs, TokenLine, _) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_0(TokenChars, TokenLine);
yyaction(1, TokenLen, YYtcs, TokenLine, _) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_1(TokenChars, TokenLine);
yyaction(2, _, _, TokenLine, _) ->
    yyaction_2(TokenLine);
yyaction(3, _, _, TokenLine, _) ->
    yyaction_3(TokenLine);
yyaction(4, _, _, TokenLine, _) ->
    yyaction_4(TokenLine);
yyaction(5, _, _, TokenLine, _) ->
    yyaction_5(TokenLine);
yyaction(6, _, _, TokenLine, _) ->
    yyaction_6(TokenLine);
yyaction(7, _, _, TokenLine, _) ->
    yyaction_7(TokenLine);
yyaction(8, _, _, _, _) ->
    yyaction_8();
yyaction(9, _, _, _, _) ->
    yyaction_9();
yyaction(10, _, _, _, _) ->
    yyaction_10();
yyaction(11, _, _, _, _) ->
    yyaction_11();
yyaction(12, _, _, _, _) ->
    yyaction_12();
yyaction(13, _, _, _, _) ->
    yyaction_13();
yyaction(14, _, _, _, _) ->
    yyaction_14();
yyaction(15, _, _, _, _) ->
    yyaction_15();
yyaction(16, _, _, _, _) ->
    yyaction_16();
yyaction(17, _, _, _, _) ->
    yyaction_17();
yyaction(18, _, _, _, _) ->
    yyaction_18();
yyaction(19, _, _, _, _) ->
    yyaction_19();
yyaction(20, _, _, _, _) ->
    yyaction_20();
yyaction(21, _, _, _, _) ->
    yyaction_21();
yyaction(22, _, _, _, _) ->
    yyaction_22();
yyaction(23, _, _, _, _) ->
    yyaction_23();
yyaction(24, _, _, _, _) ->
    yyaction_24();
yyaction(25, _, _, _, _) ->
    yyaction_25();
yyaction(26, _, _, _, _) ->
    yyaction_26();
yyaction(27, _, _, _, _) ->
    yyaction_27();
yyaction(28, _, _, _, _) ->
    yyaction_28();
yyaction(29, _, _, _, _) ->
    yyaction_29();
yyaction(30, _, _, _, _) ->
    yyaction_30();
yyaction(31, _, _, _, _) ->
    yyaction_31();
yyaction(32, _, _, _, _) ->
    yyaction_32();
yyaction(33, _, _, _, _) ->
    yyaction_33();
yyaction(34, _, _, _, _) ->
    yyaction_34();
yyaction(35, _, _, _, _) ->
    yyaction_35();
yyaction(36, _, _, _, _) ->
    yyaction_36();
yyaction(37, _, _, _, _) ->
    yyaction_37();
yyaction(38, _, _, _, _) ->
    yyaction_38();
yyaction(39, _, _, _, _) ->
    yyaction_39();
yyaction(40, _, _, _, _) ->
    yyaction_40();
yyaction(41, _, _, _, _) ->
    yyaction_41();
yyaction(42, _, _, _, _) ->
    yyaction_42();
yyaction(43, _, _, _, _) ->
    yyaction_43();
yyaction(44, _, _, _, _) ->
    yyaction_44();
yyaction(45, _, _, _, _) ->
    yyaction_45();
yyaction(46, _, _, _, _) ->
    yyaction_46();
yyaction(47, _, _, _, _) ->
    yyaction_47();
yyaction(48, _, _, _, _) ->
    yyaction_48();
yyaction(49, _, _, _, _) ->
    yyaction_49();
yyaction(50, _, _, _, _) ->
    yyaction_50();
yyaction(51, _, _, _, _) ->
    yyaction_51();
yyaction(52, _, _, _, _) ->
    yyaction_52();
yyaction(53, _, _, _, _) ->
    yyaction_53();
yyaction(54, _, _, _, _) ->
    yyaction_54();
yyaction(55, _, _, _, _) ->
    yyaction_55();
yyaction(56, _, _, _, _) ->
    yyaction_56();
yyaction(57, _, _, _, _) ->
    yyaction_57();
yyaction(58, TokenLen, YYtcs, _, _) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_58(TokenChars);
yyaction(_, _, _, _, _) -> error.

-compile({inline,yyaction_0/2}).
-file("/Users/barbarachassoul/Library/Mobile Documents/com~apple~CloudDocs/physerl/src/physerl_lexer.xrl", 6).
yyaction_0(TokenChars, TokenLine) ->
     { token, { number, TokenLine, list_to_integer (TokenChars) } } .

-compile({inline,yyaction_1/2}).
-file("/Users/barbarachassoul/Library/Mobile Documents/com~apple~CloudDocs/physerl/src/physerl_lexer.xrl", 7).
yyaction_1(TokenChars, TokenLine) ->
     { token, { number, TokenLine, list_to_float (TokenChars) } } .

-compile({inline,yyaction_2/1}).
-file("/Users/barbarachassoul/Library/Mobile Documents/com~apple~CloudDocs/physerl/src/physerl_lexer.xrl", 8).
yyaction_2(TokenLine) ->
     { token, { '^', TokenLine } } .

-compile({inline,yyaction_3/1}).
-file("/Users/barbarachassoul/Library/Mobile Documents/com~apple~CloudDocs/physerl/src/physerl_lexer.xrl", 9).
yyaction_3(TokenLine) ->
     { token, { '+', TokenLine } } .

-compile({inline,yyaction_4/1}).
-file("/Users/barbarachassoul/Library/Mobile Documents/com~apple~CloudDocs/physerl/src/physerl_lexer.xrl", 10).
yyaction_4(TokenLine) ->
     { token, { '-', TokenLine } } .

-compile({inline,yyaction_5/1}).
-file("/Users/barbarachassoul/Library/Mobile Documents/com~apple~CloudDocs/physerl/src/physerl_lexer.xrl", 11).
yyaction_5(TokenLine) ->
     { token, { '*', TokenLine } } .

-compile({inline,yyaction_6/1}).
-file("/Users/barbarachassoul/Library/Mobile Documents/com~apple~CloudDocs/physerl/src/physerl_lexer.xrl", 12).
yyaction_6(TokenLine) ->
     { token, { '/', TokenLine } } .

-compile({inline,yyaction_7/1}).
-file("/Users/barbarachassoul/Library/Mobile Documents/com~apple~CloudDocs/physerl/src/physerl_lexer.xrl", 13).
yyaction_7(TokenLine) ->
     { token, { ' ', TokenLine } } .

-compile({inline,yyaction_8/0}).
-file("/Users/barbarachassoul/Library/Mobile Documents/com~apple~CloudDocs/physerl/src/physerl_lexer.xrl", 16).
yyaction_8() ->
     { token, { unit_symbol, kg } } .

-compile({inline,yyaction_9/0}).
-file("/Users/barbarachassoul/Library/Mobile Documents/com~apple~CloudDocs/physerl/src/physerl_lexer.xrl", 17).
yyaction_9() ->
     { token, { prefix_symbol, k } } .

-compile({inline,yyaction_10/0}).
-file("/Users/barbarachassoul/Library/Mobile Documents/com~apple~CloudDocs/physerl/src/physerl_lexer.xrl", 18).
yyaction_10() ->
     { token, { unit_symbol, g } } .

-compile({inline,yyaction_11/0}).
-file("/Users/barbarachassoul/Library/Mobile Documents/com~apple~CloudDocs/physerl/src/physerl_lexer.xrl", 21).
yyaction_11() ->
     { token, { 'unit_symbol?', m } } .

-compile({inline,yyaction_12/0}).
-file("/Users/barbarachassoul/Library/Mobile Documents/com~apple~CloudDocs/physerl/src/physerl_lexer.xrl", 24).
yyaction_12() ->
     { token, { prefix_symbol, 'Q' } } .

-compile({inline,yyaction_13/0}).
-file("/Users/barbarachassoul/Library/Mobile Documents/com~apple~CloudDocs/physerl/src/physerl_lexer.xrl", 25).
yyaction_13() ->
     { token, { prefix_symbol, 'R' } } .

-compile({inline,yyaction_14/0}).
-file("/Users/barbarachassoul/Library/Mobile Documents/com~apple~CloudDocs/physerl/src/physerl_lexer.xrl", 26).
yyaction_14() ->
     { token, { prefix_symbol, 'Y' } } .

-compile({inline,yyaction_15/0}).
-file("/Users/barbarachassoul/Library/Mobile Documents/com~apple~CloudDocs/physerl/src/physerl_lexer.xrl", 27).
yyaction_15() ->
     { token, { prefix_symbol, 'Z' } } .

-compile({inline,yyaction_16/0}).
-file("/Users/barbarachassoul/Library/Mobile Documents/com~apple~CloudDocs/physerl/src/physerl_lexer.xrl", 28).
yyaction_16() ->
     { token, { prefix_symbol, 'E' } } .

-compile({inline,yyaction_17/0}).
-file("/Users/barbarachassoul/Library/Mobile Documents/com~apple~CloudDocs/physerl/src/physerl_lexer.xrl", 29).
yyaction_17() ->
     { token, { prefix_symbol, 'P' } } .

-compile({inline,yyaction_18/0}).
-file("/Users/barbarachassoul/Library/Mobile Documents/com~apple~CloudDocs/physerl/src/physerl_lexer.xrl", 30).
yyaction_18() ->
     { token, { prefix_symbol, 'T' } } .

-compile({inline,yyaction_19/0}).
-file("/Users/barbarachassoul/Library/Mobile Documents/com~apple~CloudDocs/physerl/src/physerl_lexer.xrl", 31).
yyaction_19() ->
     { token, { prefix_symbol, 'G' } } .

-compile({inline,yyaction_20/0}).
-file("/Users/barbarachassoul/Library/Mobile Documents/com~apple~CloudDocs/physerl/src/physerl_lexer.xrl", 32).
yyaction_20() ->
     { token, { prefix_symbol, 'M' } } .

-compile({inline,yyaction_21/0}).
-file("/Users/barbarachassoul/Library/Mobile Documents/com~apple~CloudDocs/physerl/src/physerl_lexer.xrl", 33).
yyaction_21() ->
     { token, { prefix_symbol, h } } .

-compile({inline,yyaction_22/0}).
-file("/Users/barbarachassoul/Library/Mobile Documents/com~apple~CloudDocs/physerl/src/physerl_lexer.xrl", 34).
yyaction_22() ->
     { token, { prefix_symbol, da } } .

-compile({inline,yyaction_23/0}).
-file("/Users/barbarachassoul/Library/Mobile Documents/com~apple~CloudDocs/physerl/src/physerl_lexer.xrl", 35).
yyaction_23() ->
     { token, { prefix_symbol, d } } .

-compile({inline,yyaction_24/0}).
-file("/Users/barbarachassoul/Library/Mobile Documents/com~apple~CloudDocs/physerl/src/physerl_lexer.xrl", 36).
yyaction_24() ->
     { token, { prefix_symbol, c } } .

-compile({inline,yyaction_25/0}).
-file("/Users/barbarachassoul/Library/Mobile Documents/com~apple~CloudDocs/physerl/src/physerl_lexer.xrl", 37).
yyaction_25() ->
     { token, { prefix_symbol, 'μ' } } .

-compile({inline,yyaction_26/0}).
-file("/Users/barbarachassoul/Library/Mobile Documents/com~apple~CloudDocs/physerl/src/physerl_lexer.xrl", 38).
yyaction_26() ->
     { token, { prefix_symbol, n } } .

-compile({inline,yyaction_27/0}).
-file("/Users/barbarachassoul/Library/Mobile Documents/com~apple~CloudDocs/physerl/src/physerl_lexer.xrl", 39).
yyaction_27() ->
     { token, { prefix_symbol, p } } .

-compile({inline,yyaction_28/0}).
-file("/Users/barbarachassoul/Library/Mobile Documents/com~apple~CloudDocs/physerl/src/physerl_lexer.xrl", 40).
yyaction_28() ->
     { token, { prefix_symbol, f } } .

-compile({inline,yyaction_29/0}).
-file("/Users/barbarachassoul/Library/Mobile Documents/com~apple~CloudDocs/physerl/src/physerl_lexer.xrl", 41).
yyaction_29() ->
     { token, { prefix_symbol, a } } .

-compile({inline,yyaction_30/0}).
-file("/Users/barbarachassoul/Library/Mobile Documents/com~apple~CloudDocs/physerl/src/physerl_lexer.xrl", 42).
yyaction_30() ->
     { token, { prefix_symbol, z } } .

-compile({inline,yyaction_31/0}).
-file("/Users/barbarachassoul/Library/Mobile Documents/com~apple~CloudDocs/physerl/src/physerl_lexer.xrl", 43).
yyaction_31() ->
     { token, { prefix_symbol, y } } .

-compile({inline,yyaction_32/0}).
-file("/Users/barbarachassoul/Library/Mobile Documents/com~apple~CloudDocs/physerl/src/physerl_lexer.xrl", 44).
yyaction_32() ->
     { token, { prefix_symbol, r } } .

-compile({inline,yyaction_33/0}).
-file("/Users/barbarachassoul/Library/Mobile Documents/com~apple~CloudDocs/physerl/src/physerl_lexer.xrl", 45).
yyaction_33() ->
     { token, { prefix_symbol, q } } .

-compile({inline,yyaction_34/0}).
-file("/Users/barbarachassoul/Library/Mobile Documents/com~apple~CloudDocs/physerl/src/physerl_lexer.xrl", 48).
yyaction_34() ->
     { token, { unit_symbol, s } } .

-compile({inline,yyaction_35/0}).
-file("/Users/barbarachassoul/Library/Mobile Documents/com~apple~CloudDocs/physerl/src/physerl_lexer.xrl", 49).
yyaction_35() ->
     { token, { unit_symbol, 'A' } } .

-compile({inline,yyaction_36/0}).
-file("/Users/barbarachassoul/Library/Mobile Documents/com~apple~CloudDocs/physerl/src/physerl_lexer.xrl", 50).
yyaction_36() ->
     { token, { unit_symbol, 'K' } } .

-compile({inline,yyaction_37/0}).
-file("/Users/barbarachassoul/Library/Mobile Documents/com~apple~CloudDocs/physerl/src/physerl_lexer.xrl", 51).
yyaction_37() ->
     { token, { unit_symbol, mol } } .

-compile({inline,yyaction_38/0}).
-file("/Users/barbarachassoul/Library/Mobile Documents/com~apple~CloudDocs/physerl/src/physerl_lexer.xrl", 52).
yyaction_38() ->
     { token, { unit_symbol, cd } } .

-compile({inline,yyaction_39/0}).
-file("/Users/barbarachassoul/Library/Mobile Documents/com~apple~CloudDocs/physerl/src/physerl_lexer.xrl", 55).
yyaction_39() ->
     { token, { unit_symbol, 'Hz' } } .

-compile({inline,yyaction_40/0}).
-file("/Users/barbarachassoul/Library/Mobile Documents/com~apple~CloudDocs/physerl/src/physerl_lexer.xrl", 56).
yyaction_40() ->
     { token, { unit_symbol, 'N' } } .

-compile({inline,yyaction_41/0}).
-file("/Users/barbarachassoul/Library/Mobile Documents/com~apple~CloudDocs/physerl/src/physerl_lexer.xrl", 57).
yyaction_41() ->
     { token, { unit_symbol, 'Pa' } } .

-compile({inline,yyaction_42/0}).
-file("/Users/barbarachassoul/Library/Mobile Documents/com~apple~CloudDocs/physerl/src/physerl_lexer.xrl", 58).
yyaction_42() ->
     { token, { unit_symbol, 'J' } } .

-compile({inline,yyaction_43/0}).
-file("/Users/barbarachassoul/Library/Mobile Documents/com~apple~CloudDocs/physerl/src/physerl_lexer.xrl", 59).
yyaction_43() ->
     { token, { unit_symbol, 'W' } } .

-compile({inline,yyaction_44/0}).
-file("/Users/barbarachassoul/Library/Mobile Documents/com~apple~CloudDocs/physerl/src/physerl_lexer.xrl", 60).
yyaction_44() ->
     { token, { unit_symbol, 'C' } } .

-compile({inline,yyaction_45/0}).
-file("/Users/barbarachassoul/Library/Mobile Documents/com~apple~CloudDocs/physerl/src/physerl_lexer.xrl", 61).
yyaction_45() ->
     { token, { unit_symbol, 'V' } } .

-compile({inline,yyaction_46/0}).
-file("/Users/barbarachassoul/Library/Mobile Documents/com~apple~CloudDocs/physerl/src/physerl_lexer.xrl", 62).
yyaction_46() ->
     { token, { unit_symbol, 'F' } } .

-compile({inline,yyaction_47/0}).
-file("/Users/barbarachassoul/Library/Mobile Documents/com~apple~CloudDocs/physerl/src/physerl_lexer.xrl", 63).
yyaction_47() ->
     { token, { unit_symbol, 'Ohm' } } .

-compile({inline,yyaction_48/0}).
-file("/Users/barbarachassoul/Library/Mobile Documents/com~apple~CloudDocs/physerl/src/physerl_lexer.xrl", 64).
yyaction_48() ->
     { token, { unit_symbol, 'S' } } .

-compile({inline,yyaction_49/0}).
-file("/Users/barbarachassoul/Library/Mobile Documents/com~apple~CloudDocs/physerl/src/physerl_lexer.xrl", 65).
yyaction_49() ->
     { token, { unit_symbol, 'Wb' } } .

-compile({inline,yyaction_50/0}).
-file("/Users/barbarachassoul/Library/Mobile Documents/com~apple~CloudDocs/physerl/src/physerl_lexer.xrl", 66).
yyaction_50() ->
     { token, { unit_symbol, 'T' } } .

-compile({inline,yyaction_51/0}).
-file("/Users/barbarachassoul/Library/Mobile Documents/com~apple~CloudDocs/physerl/src/physerl_lexer.xrl", 67).
yyaction_51() ->
     { token, { unit_symbol, 'H' } } .

-compile({inline,yyaction_52/0}).
-file("/Users/barbarachassoul/Library/Mobile Documents/com~apple~CloudDocs/physerl/src/physerl_lexer.xrl", 68).
yyaction_52() ->
     { token, { unit_symbol, lm } } .

-compile({inline,yyaction_53/0}).
-file("/Users/barbarachassoul/Library/Mobile Documents/com~apple~CloudDocs/physerl/src/physerl_lexer.xrl", 69).
yyaction_53() ->
     { token, { unit_symbol, lx } } .

-compile({inline,yyaction_54/0}).
-file("/Users/barbarachassoul/Library/Mobile Documents/com~apple~CloudDocs/physerl/src/physerl_lexer.xrl", 70).
yyaction_54() ->
     { token, { unit_symbol, 'Bq' } } .

-compile({inline,yyaction_55/0}).
-file("/Users/barbarachassoul/Library/Mobile Documents/com~apple~CloudDocs/physerl/src/physerl_lexer.xrl", 71).
yyaction_55() ->
     { token, { unit_symbol, 'Gy' } } .

-compile({inline,yyaction_56/0}).
-file("/Users/barbarachassoul/Library/Mobile Documents/com~apple~CloudDocs/physerl/src/physerl_lexer.xrl", 72).
yyaction_56() ->
     { token, { unit_symbol, 'Sv' } } .

-compile({inline,yyaction_57/0}).
-file("/Users/barbarachassoul/Library/Mobile Documents/com~apple~CloudDocs/physerl/src/physerl_lexer.xrl", 73).
yyaction_57() ->
     { token, { unit_symbol, kat } } .

-compile({inline,yyaction_58/1}).
-file("/Users/barbarachassoul/Library/Mobile Documents/com~apple~CloudDocs/physerl/src/physerl_lexer.xrl", 75).
yyaction_58(TokenChars) ->
     { error, { illegal_token, TokenChars } } .
-file("/Users/barbarachassoul/.asdf/installs/erlang/26.2.5.4/lib/parsetools-2.5/include/leexinc.hrl", 344).
